---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cxp-deployer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cxp-deployer
  namespace: cxp-sandbox
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "pods"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cxp-deployer
  namespace: cxp-sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cxp-deployer
subjects:
  - kind: ServiceAccount
    name: cxp-deployer
    namespace: {{ .Release.Namespace }}
